### ISSUE TITLE
Labels not properly displayed on list pages

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/magento2-module-product-label#11]
Only the first product has a label displayed on a list page.

Most probably because of the javascript code : 

```js
        $(".productlabel-wrapper")[0].style.width = widthOfParent + "px";
        $(".productlabel-wrapper")[0].style.height = heightOfParent + "px";
```

With `[0]` it only applies to the first matched element instead of applying on all labels in the page.

**Comment by houdaElr** [comment]
it's not js but because a stylesheet, i put a position on abosulte.
Can you check if it's ok?
