### ISSUE TITLE
Error in Store Table Product labels

### ISSUE THREAD

**Issue by GabrielFNLima** [Smile-SA/magento2-module-product-label#20]
After the installation the following error occurred:
Fatal error: Interface 'Smile\ProductLabel\Api\ProductLabelRepositoryInterface' not found in /app/code/Smile/ProductLabel/Model/Repository/ProductLabel.php on line 33

**Comment by romainruaud** [comment]
How did you install the module ? it's meant to be installed via composer, since it's located on app/code on your environment, I guess it's not the case.

Regards
