### ISSUE TITLE
Error when installing on Magento 2.2.7

### ISSUE THREAD

**Issue by itprorange** [Smile-SA/magento2-module-product-label#21]
Environment:
- Magento 2.2.7 CE 
- PHP 7.1
- Composer version 1.8.0 2018-12-03 10:31:16

### While trying to install using composer install smile/module-product-label, The following message appears:

Invalid argument smile/module-product-label. Use "composer require smile/module-product-label" instead to add packages to your composer.json.

### While trying to install using composer require smile/module-product-label, The following error appears:

Using version ^1.1 for smile/module-product-label
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install composer/composer 1.8.6
    - Conclusion: don't install composer/composer 1.8.5
    - Conclusion: don't install composer/composer 1.8.4
    - Conclusion: don't install composer/composer 1.8.3
    - Conclusion: don't install composer/composer 1.8.2
    - Conclusion: don't install composer/composer 1.8.1
    - Conclusion: don't install composer/composer 1.8.0
    - Conclusion: don't install composer/composer 1.7.3
    - Conclusion: don't install composer/composer 1.7.2
    - Conclusion: don't install composer/composer 1.7.1
    - Conclusion: don't install composer/composer 1.7.0
    - Conclusion: don't install composer/composer 1.7.0-RC
    - Conclusion: don't install composer/composer 1.6.5
    - Conclusion: don't install composer/composer 1.6.4
    - Conclusion: don't install composer/composer 1.6.3
    - Conclusion: don't install composer/composer 1.6.2
    - Conclusion: don't install composer/composer 1.6.1
    - Conclusion: don't install composer/composer 1.6.0
    - Installation request for magento/product-community-edition 2.2.7 -> satisfiable by magento/product-community-edition[2.2.7].
    - smile/module-product-label 1.1.0 requires magento/framework ^102.0.0 -> satisfiable by magento/framework[102.0.0, 102.0.1, 102.0.2].
    - smile/module-product-label 1.1.1 requires magento/framework ^102.0.0 -> satisfiable by magento/framework[102.0.0, 102.0.1, 102.0.2].
    - magento/framework 102.0.2 requires composer/composer ^1.6 -> satisfiable by composer/composer[1.6.0, 1.6.0-RC, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.0-RC, 1.7.1, 1.7.2, 1.7.3, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6].
    - magento/framework 102.0.1 requires composer/composer ^1.6 -> satisfiable by composer/composer[1.6.0, 1.6.0-RC, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.0-RC, 1.7.1, 1.7.2, 1.7.3, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6].
    - magento/framework 102.0.0 requires composer/composer ^1.6 -> satisfiable by composer/composer[1.6.0, 1.6.0-RC, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.0-RC, 1.7.1, 1.7.2, 1.7.3, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6].
    - Conclusion: don't install composer/composer 1.6.0-RC
    - Installation request for smile/module-product-label ^1.1 -> satisfiable by smile/module-product-label[1.1.0, 1.1.1].

Installation failed, reverting ./composer.json to its original content.

###  While trying to install Manually, so many errors appear, starting from compilation issues:

[Exception]
  Warning: Declaration of Smile\ProductLabel\Block\Product\ImageFactory::create(Magento\Catalog\Model\Product $product, string $imageId, ?array $attributes = NULL): Magento\Catalog\Block\Product\Image should be compatible with Magento\Catalog\Block\Product\ImageFactory::create(array $data = Array) in /home/warredly/test.warredly.com/dev/app/code/Smile/ProductLabel/Block/Product/ImageFactory.php on

**Comment by killday** [comment]
Much of the same problem here. 

Magento 2.2.0
PHP 7.1
Composer version 1.6.2 2018-01-05 15:28:41

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - smile/module-product-label 1.1.1 requires magento/framework ^102.0.0 -> no matching package found.
    - smile/module-product-label 1.1.0 requires magento/framework ^102.0.0 -> no matching package found.
    - Installation request for smile/module-product-label ^1.1 -> satisfiable by smile/module-product-label[1.1.0, 1.1.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

**Comment by romainruaud** [comment]
Hello,

Magento <2.3.0 is not supported by this module.

Regards

**Comment by killday** [comment]
Hi,
OK thanks, just add this as an information in the readme and the documentation.
