### ISSUE TITLE
line up the symbols horizontal

### ISSUE THREAD

**Issue by visenco** [Smile-SA/magento2-module-product-label#22]
IS there a possibilty to line up the label from left to right ? I am getting them now vertical https://www.cookingismylife.com/nl/nonfood/pannen/wokpan.html/baumalu-rvs-inox-wok-36-cm-o-4-delig.html

Would be nice if you would be able to line them up.

**Comment by killday** [comment]
That's simple, you need to play with the css a bit. Remove the max-width:10%; property for top_left product.
Then create a class for the images and set their  max-width:10%; 

Result:

![image](https://user-images.githubusercontent.com/6714294/64906294-9efc6100-d6dc-11e9-9ec2-ccc49b499e51.png)
