### ISSUE TITLE
di:compile returns error on Magento 2.2.8

### ISSUE THREAD

**Issue by ebofi** [Smile-SA/magento2-module-product-label#26]
Issues:
1.All products on the site front end is not showing, 
2. di compile CLI returns error

Error Log

PHP Fatal error:  Interface 'Magento\Framework\Setup\Patch\DataPatchInterface' not found in /chroot/home/cptech/cphomeorig/public_html/app/code/Smile/ProductLabel/Setup/Patch/Data/UpdateExistingLabelsStoreView.php on line 26

Fatal error: Interface 'Magento\Framework\Setup\Patch\DataPatchInterface' not found in /chroot/home/cptech/cphomeorig/public_html/app/code/Smile/ProductLabel/Setup/Patch/Data/UpdateExistingLabelsStoreView.php on line 26

**Comment by cemag44300** [comment]
Hello @ebofi  , I have just published a new version of the module, you can see if that fixes your problem.
https://github.com/Smile-SA/magento2-module-product-label/releases/tag/1.2.0
