### ISSUE TITLE
Module only checks custom attributes

### ISSUE THREAD

**Issue by Quillatyam** [Smile-SA/magento2-module-product-label#28]
We ran into this issue when using the standard attribute 'visibility'. 

The module only checks with `$this->getProduct()->getCustomAttribute($attribute->getAttributeCode());`, but that doesn't return selected options for 'standard attributes (which you would get with `$this->getProduct()->getData($attribute->getAttributeCode());`)

I made a (quick-and-dirty) patch working around this issue, I'll attach that to make it clearer what I mean.
[SMILE-MODULE-PRODUCT-LABEL1.1.1_CUSTOM_ATTRIBUTES.txt](https://github.com/Smile-SA/magento2-module-product-label/files/4307606/SMILE-MODULE-PRODUCT-LABEL1.1.1_CUSTOM_ATTRIBUTES.txt)

**Comment by cptX** [comment]
Does this patch corrects the issue of not showing all the available attributes when setting the labels?
