### ISSUE TITLE
Search field on the backend does not seem to work : remove it ?

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/magento2-module-product-label#3]
![Sélection_641](https://user-images.githubusercontent.com/15340849/54143431-1d283400-442a-11e9-9b46-b09fb79970e5.png)

This field always give me all the product labels, event if I type something which is not existing.

You can remove the field, it's probably easier than making it working.

**Comment by houdaElr** [comment]
Done.

**Comment by romainruaud** [comment]
Tested OK for me, thank you !
