### ISSUE TITLE
I can not choose from all existing attributes

### ISSUE THREAD

**Issue by andihuber** [Smile-SA/magento2-module-product-label#31]
Hello,

when i add a new label i can not choose from all existing product attributes.

Some are in the list under "Attributes", some not. 

Magento 2.3.2 / Extension version 1.1.1

Thank you,
BR Andreas

**Comment by shashank141097** [comment]
Hello,
any update on this issue?

**Comment by jmpedrosa** [comment]
me too!

**Comment by andihuber** [comment]
No, unfortunately no update on this. :-(

**Comment by indunie** [comment]
Hey, 
Any update on this?
I could see all attributes which has setup before the plugin installation. Post creating attributes are not syncing with the label attribute dropdown.

Thank you.
Indunie Florence

**Comment by cptX** [comment]
Attributes of type YES/NO are not detected by this module. This is critical and need to be fixed!
