### ISSUE TITLE
Does not work with Magento 2.4

### ISSUE THREAD

**Issue by suryawomshi** [Smile-SA/magento2-module-product-label#33]
Not Installing due to dependency.

smile/module-product-label 1.1.1 requires magento/framework ^102.0.0

**Comment by shizuka-nakamura** [comment]
hi @suryawomshi 

Did you resolved this problem? if yes, please share me the solution. 
Thank you so much

**Comment by hardik2905** [comment]
> Not Installing due to dependency.
> 
> smile/module-product-label 1.1.1 requires magento/framework ^102.0.0

I am also having same issue.

**Comment by chernoux** [comment]
The dependencies problem has be corrected in the version 1.1.2.
