### ISSUE TITLE
Problem istallation Magento 2.3.6

### ISSUE THREAD

**Issue by Danieleeffe1** [Smile-SA/magento2-module-product-label#34]
God morning and sorry for my english .

I have a problem for installing this module.
In My Hosting 

I from Magento1
I'm new user of magento2 
In magento 1 i not use composer

I have installing varius module in magento 2 in manual mode but this module not have instruction for this way.

I have crate folder  in magento root /app/code/Smile/ProductLabel 

I have unzip file magento2-module-product-label-master.zip and i copied the unzipped files in the ProductLabel 

I have add and enable module in Magento root /app/etc/config.php

I the virtual termina of my hosting i have run the command : php ./bin/magento setup:upgrade

The reminal return this error:
 
Unable to apply data patch Smile\ProductLabel\Setup\Patch\Data\UpdateExistingLabelsStoreView for module Smile_ProductLabel. Original exception message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxx_xxx771.smile_productlabel' doesn't exist, query was: SELECT `smile_productlabel`.`product_label_id`, 0 as store_id FROM `smile_productlabel`

Please help my

**Comment by Danieleeffe1** [comment]
Update my report

If i try manual installation the server print this message:

Warning: call_user_func() expects parameter 1 to be a valid callback, class 'Smile\ProductLabel\Setup\Patch\Data\UpdateExistingLabelsStoreView' not found in /home/myuser/m2.mydomain.com/vendor/magento/framework/Setup/Patch/PatchRegistry.php on line 141

**Comment by chernoux** [comment]
The dependencies problem has be corrected in the version 1.1.2.

**Comment by cemag44300** [comment]
Hello @Danieleeffe1 , I have just published a new version of the module, you can see if that fixes your problem.
https://github.com/Smile-SA/magento2-module-product-label/releases/tag/1.2.0
