### ISSUE TITLE
Error while saving the label :  Integrity constraint violation

### ISSUE THREAD

**Issue by indunie** [Smile-SA/magento2-module-product-label#36]
Hi team,
I installed the module to my project and tried to create my first badge there.
But having this error message.

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`smile_productlabel`, CONSTRAINT `SMILE_PRODUCTLABEL_OPTION_ID_EAV_ATTRIBUTE_OPTION_OPTION_ID` FOREIGN KEY (`option_id`) REFERENCES `eav_attribute_option` (`option_id`) ON DELETE CAS), query was: INSERT INTO `smile_productlabel` (`product_label_id`, `is_active`, `name`, `attribute_id`, `option_id`, `image`, `position_category_list`, `position_product_view`, `alt`, `display_on`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

Magento version : 2.4
I tried removing caches, reindexing and permission changing. Still no luck. 

Could someone help me please.
Thank you.

Best Regards,
Indunie Florence

**Comment by git-seb** [comment]
At this moment, this issue still exists in Magento 2.4.5-p1.

**Comment by cemag44300** [comment]
Hello @indunie, i update a magento instance to 2.4.5-p1 and i try to create a label and i don't see the error message.
https://i.imgur.com/TVHu2HN.png

Can you help me to solve your problem ?

**Comment by git-seb** [comment]
@cemag44300 Hi Semag, I got new information regarding this issue. When I tested, I tried using the Visilibity attrbiute and selected Catalog, Search. Selecting this and saving shows the SQL error. I just tried with a different attribute (manufacturer) and this worked fine.

**Comment by PierreGauthier** [comment]
Hello @git-seb ,
This have been fixed by  3a9cbe0b  and  31ef4d33
