### ISSUE TITLE
Error: Call to undefined method Magento\Catalog\Api\Data\ProductExtension::getProductLabels()

### ISSUE THREAD

**Issue by trubnikovr** [Smile-SA/magento2-module-product-label#37]
Good day. 
magento 2.4.3 
after install your module via composer, i am facing the error in backend 
Error: Call to undefined method Magento\Catalog\Api\Data\ProductExtension::getProductLabels()

**Comment by cemag44300** [comment]
Hello @trubnikovr  , I have just published a new version of the module, you can see if that fixes your problem.
https://github.com/Smile-SA/magento2-module-product-label/releases/tag/1.2.0
