### ISSUE TITLE
SOAP api is broken

### ISSUE THREAD

**Issue by LotsofPixels** [Smile-SA/magento2-module-product-label#38]
After installing the module is, the salesOrderRepositoryV1 in SOAP is returning an error: The array class doesn't exist and the namespace must be specified. Verify and try again

This is caused by Api/Data/ProductLabelInterface.php

@@ -170,7 +170,7 @@
     /**
      * Get display_on
      *
-     * @return mixed[]
+     * @return array
      */
     public function getDisplayOn();

**Comment by PierreGauthier** [comment]
Hello
This has been fixed by https://github.com/Smile-SA/magento2-module-product-label/pull/60
