### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/magento2-module-product-label#4]
On the back-office there are some strings that are not translated : 

- "Manage Product labels"

- "Add New Attribute" (this one could be "Add New Label")

- "Change status" action on the grid

- "Save Product Label" on the edit screen

- "Delete Product Label" on the edit screen

**Comment by houdaElr** [comment]
Done.

**Comment by romainruaud** [comment]
Tested OK for me, thank you !
