### ISSUE TITLE
M2.4.5-p1 - bug in admin grid making each record show the same data [Smile_ProductLabel 1.2.4]

### ISSUE THREAD

**Issue by pcvvelzen** [Smile-SA/magento2-module-product-label#57]
Current situation: This issue was encountered coming from a working situation with Magento `2.3.x` and Smile_ProductLabel `1.1.x`, issue found during upgrading to Magento to `2.4.5-p1` with latest version of Smile_ProductLabel `1.2.4` module.

This issue is related to a combination to a newer Magento and Smile_ProductLabel version, specifically `2.4.5-p1` and module `v1.2.4` which are confirmed on a clean Magento codebase following these steps to reproduce:

- Install and finish installation a fresh Magento `2.4.5-p1` setup:
https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/composer.html#example---security-patch
- Composer install the module:
https://github.com/Smile-SA/magento2-module-product-label/wiki/GettingStarted
- Create two different product labels through the Magento admin (like 'Test1' and 'Test2') under _Marketing > Smile Pictos > Labels_

The issue: 
After saving the second label the admin grid shows correct amount of results but only the info from the last created record at each row
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/19436743/222211703-53e65240-a15e-4a33-ac37-37de9f7869c9.png">

**Comment by cemag44300** [comment]
@pcvvelzen Thank you for your report and your PR.
I will check this today and do a new release
