### ISSUE TITLE
Product Label not showing Product view & List

### ISSUE THREAD

**Issue by MrLuanVC** [Smile-SA/magento2-module-product-label#63]
I have a new Magento 2.4

Alter install module product-label and create new label, but done front-end product label not available.

![image](https://github.com/Smile-SA/magento2-module-product-label/assets/111330792/260aa826-ea13-4cb3-b243-0a17e1a4f3de)

![image](https://github.com/Smile-SA/magento2-module-product-label/assets/111330792/d0f70c77-f664-49c2-8bd1-34ad32739bfc)

Please help

**Comment by PierreGauthier** [comment]
Hello @MrLuanVC ,
This issue has been fixed by 3a9cbe0b
